# Generated by Django 4.2.7 on 2025-10-27 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ast_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='仓库名称', max_length=255, unique=True)),
                ('url', models.URLField(help_text='Git仓库URL', max_length=500)),
                ('branch', models.CharField(default='main', help_text='分支名称', max_length=100)),
                ('local_path', models.TextField(help_text='本地克隆路径')),
                ('apex_dir', models.CharField(default='force-app/main/default/classes', help_text='Apex代码相对目录', max_length=500)),
                ('is_active', models.BooleanField(default=False, help_text='是否为当前活动仓库')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'repositories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='astfile',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='astfile',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ast_files', to='ast_api.repository'),
        ),
        migrations.AlterUniqueTogether(
            name='astfile',
            unique_together={('repository', 'filename')},
        ),
    ]
