# Generated by Django 4.2.7 on 2025-10-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ast_api', '0002_repository_alter_astfile_filename_astfile_repository_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astfile',
            name='source_code_path',
            field=models.TextField(blank=True, help_text='源代码文件路径', null=True),
        ),
    ]
